# Generated by Django 3.0.6 on 2020-05-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200505_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='images/already.png', upload_to='images/'),
        ),
    ]
